### ISSUE TITLE
Extract timestamp from time-based UUIDs

### ISSUE THREAD

**Issue by ybasket** [ant8e/uuid4cats-effect#65]
Hello,
glad to have the honour of writing the first issue 😄 

The project looks quite promising and I'd love to adopt it at $WORK, ditching `com.github.f4b6a3:uuid-creator`, but there's a missing piece of functionality we'd require: extracting timestamps from UUIDv6 and v7 by looking at the time-encoding bits. So something like

```scala
object UUID4CatsEffect {
  // could also return Option[Long] with epoch millis or be overloaded
  def extractTimestamp(uuid: UUID): Option[java.time.Instant] = ... 
}
```

Inspired by [UUIDUtil.getInstant](https://javadoc.io/static/com.github.f4b6a3/uuid-creator/5.3.7/com.github.f4b6a3.uuid/com/github/f4b6a3/uuid/util/UuidUtil.html#getInstant(java.util.UUID)).

I'm not sure I can find the time to contribute, but in any way would be glad if this feature made it into the library.

**Comment by ant8e** [comment]
Hi,
Congrats on filling the first issue !

This is great suggestions, thanks. I will look into it, it should not be too much of a deal.

**Comment by ant8e** [comment]
#66 is addressing this.
